name: Gitee repos mirror periodic job

on:
  pull_request:
    paths:
    - '.github/workflows/**'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@python
      with:
        src: github/kunpengcompute
        dst: gitee/kunpengcompute
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        account_type: org
        timeout: 600
        force_update: true
        black_list: "mysql-server,kunpeng-mpam,hadoop,kunpengcompute.github.io"
